name: vocdoni
description: Decentralized anonymous E2E verifiable voting system client app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.4+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dvote: ^0.6.0
  webview_flutter: ^0.3.10+3
  provider: ^3.2.0
  protobuf: ^0.13.15
  flutter_localizations:
    sdk: flutter
  native_widgets: ^1.3.5
  uni_links: ^0.2.0
  http: ^0.12.0+2
  feather_icons_flutter: ^4.7.4
  flutter_html: ^0.10.4
  url_launcher: ^5.1.0
  path_provider: ^1.2.0
  mixpanel_analytics: ^1.1.0
  qrcode_reader:
    git:
      url: https://github.com/bcko/flutter_qrcode_reader.git
      ref: android_fix

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
      - family: Open Sans
        fonts:
          - asset: assets/fonts/OpenSans-Light.ttf
            weight: 300
          - asset: assets/fonts/OpenSans-Regular.ttf
            weight: 400
          - asset: assets/fonts/OpenSans-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/OpenSans-Bold.ttf
            weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #assets:
  # TODO: CHANGE
    #- assets/media/calendar.png
    #- assets/media/home.png
    #- assets/media/house.png
    #- assets/media/mountain.png
    #- assets/media/plane.png
    #- assets/media/world.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
